from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError
import time

def login_and_save_cookies_netscape(email, password, cookies_path='cookies.txt'):
    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=False,
            args=[
                "--disable-blink-features=AutomationControlled",
                "--no-sandbox",
                "--disable-dev-shm-usage",
            ],
        )
        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                       "AppleWebKit/537.36 (KHTML, like Gecko) "
                       "Chrome/114.0.0.0 Safari/537.36"
        )
        page = context.new_page()

        # Go to Google login page
        page.goto("https://accounts.google.com/signin/v2/identifier")

        # Enter email
        page.wait_for_selector('input[type="email"]', timeout=10000)
        page.fill('input[type="email"]', email)
        page.click('button:has-text("Next")')

        # Enter password
        page.wait_for_selector('input[type="password"]', timeout=10000)
        page.fill('input[type="password"]', password)
        page.click('button:has-text("Next")')

        # Wait for any navigation after login
        try:
            page.wait_for_load_state("networkidle", timeout=30000)
            print("Logged in successfully!")
        except PlaywrightTimeoutError:
            print("Page did not finish loading in time after login; check for 2FA or extra steps.")

        # Navigate to YouTube to get YouTube cookies
        page.goto("https://www.youtube.com")
        page.wait_for_load_state("networkidle", timeout=20000)
        print("Navigated to YouTube, ready to get cookies.")

        # Get cookies from context
        cookies = context.cookies()

        # Convert cookies to Netscape format
        lines = [
            "# Netscape HTTP Cookie File",
            "# This file is generated by Playwright automation",
            ""
        ]

        for c in cookies:
            domain = c['domain']
            flag = "TRUE" if domain.startswith('.') else "FALSE"
            path = c['path']
            secure = "TRUE" if c['secure'] else "FALSE"
            expires = str(c['expires']) if c['expires'] else "0"
            name = c['name']
            value = c['value']
            line = "\t".join([domain, flag, path, secure, expires, name, value])
            lines.append(line)

        # Write to file
        with open(cookies_path, 'w') as f:
            f.write("\n".join(lines))

        print(f"Cookies saved in Netscape format to {cookies_path}")

        browser.close()

# Example usage:
login_and_save_cookies_netscape('crce.9939.ce@gmail.com', 'crce.9939.ce@7769030868')
