name: Fetch YouTube Cookies

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Google email for login'
        required: true
        default: ''
      password:
        description: 'Google password for login'
        required: true
        default: ''

jobs:
  fetch-cookies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run Playwright script
        run: |
          python fetch_cookies.py "${{ github.event.inputs.email }}" "${{ github.event.inputs.password }}"

      - name: Upload cookies.txt
        uses: actions/upload-artifact@v4
        with:
          name: cookies
          path: cookies.txt
